### ISSUE TITLE
require "eth" aborts irb / rails server on 2.7.2p137

### ISSUE THREAD

**Issue by 5hanth** [se3000/ruby-eth#54] opened 2021-03-15 20:20 UTC
```
✗ irb
2.7.2 :001 > require "eth"
[1]    91953 abort      irb
➜  app git:(main) ✗ ruby -v
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
```

**Comment by k0shima** [comment] 2021-04-30 10:40
@5hanth 
try this
https://github.com/se3000/ruby-eth/issues/47#issuecomment-610965751

**Comment by 5hanth** [comment] 2021-06-28 19:14
apparently, I was never able to use `ruby-eth` and wrote a coin manager (node.js) that runs independently with private keys of hot wallet that solely takes requests from the app server in a VPC.

**Comment by q9f** [comment] 2021-10-27 17:17
duplicate of #47

**Closed as completed by q9f** 2021-10-27 17:17 UTC
