### ISSUE TITLE
The contract code couldn't be stored, please check your gas amount.

### ISSUE THREAD

**Issue by MitchK** [se3000/ruby-eth#2] opened 2016-11-10 19:37 UTC
I have these options:

```
options  = {:nonce=>1048598, 
data: "0x606060405260016000600050556000600460006101000a81548160ff021916908302179055506040516105db3803806105db833981016040528080519060200190919080518201919060200150505b33600160006101000a81548173ffffffffffffffffffffffffffffffffffffffff0219169083021790555081600260006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908302179055508060036000509080519060200190828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106100f357805160ff1916838001178555610124565b82800160010185558215610124579182015b82811115610123578251826000505591602001919060010190610105565b5b50905061014f9190610131565b8082111561014b5760008181506000905550600101610131565b5090565b5050426005600050819055505b505061046f8061016c6000396000f36060604052361561007f576000357c0100000000000000000000000000000000000000000000000000000000900480631b3012a3146100845780631d1438481461010457806338af3eed1461014257806354fd4d501461018057806363d256ce146101a857806365b2a863146101d2578063b80777ea1461022d5761007f565b610002565b34610002576100966004805050610255565b60405180806020018281038252838181518152602001915080519060200190808383829060006004602084601f0104600302600f01f150905090810190601f1680156100f65780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b346100025761011660048050506102f6565b604051808273ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b3461000257610154600480505061031c565b604051808273ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34610002576101926004805050610342565b6040518082815260200191505060405180910390f35b34610002576101ba600480505061034b565b60405180821515815260200191505060405180910390f35b346100025761022b6004808035906020019082018035906020019191908080601f01602080910402602001604051908101604052809392919081815260200183838082843782019150505050505090909190505061035e565b005b346100025761023f6004805050610466565b6040518082815260200191505060405180910390f35b60036000508054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156102ee5780601f106102c3576101008083540402835291602001916102ee565b820191906000526020600020905b8154815290600101906020018083116102d157829003601f168201915b505050505081565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b600260009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b60006000505481565b600460009054906101000a900460ff1681565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff161415156103ba57610002565b6001600460006101000a81548160ff021916908302179055507f266095b5af7e2323760fef151f1d78896740cd2cc1b73a6357ff9e4c3fdae7408160405180806020018281038252838181518152602001915080519060200190808383829060006004602084601f0104600302600f01f150905090810190601f1680156104555780820380516001836020036101000a031916815260200191505b509250505060405180910390a15b50565b60056000505481560000000000000000000000001be31a94361a391bbafb2a4ccd704f57dc04d4bb0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000004065336230633434323938666331633134396166626634633839393666623932343237616534316534363439623933346361343935393931623738353262383535", 
value: 0, 
gas_price: 20697833099, 
gas_limit: 3000000}

tx = Eth::Tx.new(options)
tx.sign keys

...
```

When I can sendRawTransaction, ```geth``` gives me:
```
error:  Error: The contract code couldn't be stored, please check your gas amount.
```

When I use ```ethereum-tx``` (https://github.com/ethereumjs/ethereumjs-tx), I use the same parameters (but hex encoded in canonical form (with difference nonce, of course. Nonce is determined dynamically.)

```
{ nonce: '0x100016',
  data: '0x606060405260016000600050556000600460006101000a81548160ff021916908302179055506040516105db3803806105db833981016040528080519060200190919080518201919060200150505b33600160006101000a81548173ffffffffffffffffffffffffffffffffffffffff0219169083021790555081600260006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908302179055508060036000509080519060200190828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106100f357805160ff1916838001178555610124565b82800160010185558215610124579182015b82811115610123578251826000505591602001919060010190610105565b5b50905061014f9190610131565b8082111561014b5760008181506000905550600101610131565b5090565b5050426005600050819055505b505061046f8061016c6000396000f36060604052361561007f576000357c0100000000000000000000000000000000000000000000000000000000900480631b3012a3146100845780631d1438481461010457806338af3eed1461014257806354fd4d501461018057806363d256ce146101a857806365b2a863146101d2578063b80777ea1461022d5761007f565b610002565b34610002576100966004805050610255565b60405180806020018281038252838181518152602001915080519060200190808383829060006004602084601f0104600302600f01f150905090810190601f1680156100f65780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b346100025761011660048050506102f6565b604051808273ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b3461000257610154600480505061031c565b604051808273ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34610002576101926004805050610342565b6040518082815260200191505060405180910390f35b34610002576101ba600480505061034b565b60405180821515815260200191505060405180910390f35b346100025761022b6004808035906020019082018035906020019191908080601f01602080910402602001604051908101604052809392919081815260200183838082843782019150505050505090909190505061035e565b005b346100025761023f6004805050610466565b6040518082815260200191505060405180910390f35b60036000508054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156102ee5780601f106102c3576101008083540402835291602001916102ee565b820191906000526020600020905b8154815290600101906020018083116102d157829003601f168201915b505050505081565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b600260009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b60006000505481565b600460009054906101000a900460ff1681565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff161415156103ba57610002565b6001600460006101000a81548160ff021916908302179055507f266095b5af7e2323760fef151f1d78896740cd2cc1b73a6357ff9e4c3fdae7408160405180806020018281038252838181518152602001915080519060200190808383829060006004602084601f0104600302600f01f150905090810190601f1680156104555780820380516001836020036101000a031916815260200191505b509250505060405180910390a15b50565b60056000505481560000000000000000000000001be31a94361a391bbafb2a4ccd704f57dc04d4bb0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000004065336230633434323938666331633134396166626634633839393666623932343237616534316534363439623933346361343935393931623738353262383535',
  value: '0x00',
  gasPrice: '0x4d1afde8b',
  gasLimit: '0x2DC6C0' 
}
```
The only difference is the nonce, but that is certainly not the issue.

**Comment by se3000** [comment] 2016-11-11 06:23
Interesting. These are being sent from the same account?

Can you post the raw hex generated for the transactions, from both ruby and javascript?

**Comment by se3000** [comment] 2016-11-13 17:44
Hi, looking into this more and having trouble reproducing it. I was able to successfully confirm a transaction with all the same parameters, except nonce, on a local private instance of geth.

It is possible that a nonce being off is preventing your transaction from confirming. Can you share more details about how you're broadcasting the transaction, or how you're seeing the error if it's in a later step?

**Comment by MitchK** [comment] 2016-11-15 18:17
Hi, thank you for your quick response!

I'm running on a Geth node ```Geth/v1.4.18-stable-c72f5459/darwin/go1.7.3``` on Morden network. I have a Node.js service that provides an API for 

- Encoding functionality
- Sending raw transactions. (inner call is ```sendRawTransaction(...)```)

Ruby code:
```
keys = Eth::Key.new priv: "1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef"

# Contract constructor args
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
beneficiary_address = "0x01234567890abcdef01234567890abcdef012345" # arbitrary address
params = [beneficiary_address, hash]

# ABI + code
abi = [{"constant":true,"inputs":[],"name":"dataHash","outputs":[{"name":"","type":"string"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"issuer","outputs":[{"name":"","type":"address"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"beneficiary","outputs":[{"name":"","type":"address"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"version","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"revoked","outputs":[{"name":"","type":"bool"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_reason","type":"string"}],"name":"revoke","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"timestamp","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"inputs":[{"name":"_beneficiary","type":"address"},{"name":"_dataHash","type":"string"}],"type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"name":"reason","type":"string"}],"name":"CertificateRevoked","type":"event"}]
code = "606060405260016000600050556000600460006101000a81548160ff021916908302179055506040516105db3803806105db833981016040528080519060200190919080518201919060200150505b33600160006101000a81548173ffffffffffffffffffffffffffffffffffffffff0219169083021790555081600260006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908302179055508060036000509080519060200190828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106100f357805160ff1916838001178555610124565b82800160010185558215610124579182015b82811115610123578251826000505591602001919060010190610105565b5b50905061014f9190610131565b8082111561014b5760008181506000905550600101610131565b5090565b5050426005600050819055505b505061046f8061016c6000396000f36060604052361561007f576000357c0100000000000000000000000000000000000000000000000000000000900480631b3012a3146100845780631d1438481461010457806338af3eed1461014257806354fd4d501461018057806363d256ce146101a857806365b2a863146101d2578063b80777ea1461022d5761007f565b610002565b34610002576100966004805050610255565b60405180806020018281038252838181518152602001915080519060200190808383829060006004602084601f0104600302600f01f150905090810190601f1680156100f65780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b346100025761011660048050506102f6565b604051808273ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b3461000257610154600480505061031c565b604051808273ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34610002576101926004805050610342565b6040518082815260200191505060405180910390f35b34610002576101ba600480505061034b565b60405180821515815260200191505060405180910390f35b346100025761022b6004808035906020019082018035906020019191908080601f01602080910402602001604051908101604052809392919081815260200183838082843782019150505050505090909190505061035e565b005b346100025761023f6004805050610466565b6040518082815260200191505060405180910390f35b60036000508054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156102ee5780601f106102c3576101008083540402835291602001916102ee565b820191906000526020600020905b8154815290600101906020018083116102d157829003601f168201915b505050505081565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b600260009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b60006000505481565b600460009054906101000a900460ff1681565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff161415156103ba57610002565b6001600460006101000a81548160ff021916908302179055507f266095b5af7e2323760fef151f1d78896740cd2cc1b73a6357ff9e4c3fdae7408160405180806020018281038252838181518152602001915080519060200190808383829060006004602084601f0104600302600f01f150905090810190601f1680156104555780820380516001836020036101000a031916815260200191505b509250505060405180910390a15b50565b6005600050548156"

# Create payload
# uri = URI('http://127.0.0.1:5000/api/solidity/encodeConstructorParams')
# req = Net::HTTP::Post.new(uri, 'Content-Type' => 'application/json')
# req.body = {
# 	abi: abi, 
# 	params: params
# }.to_json
# res = Net::HTTP.start(uri.hostname, uri.port) { |http| http.request(req) }
# res_hash = JSON.parse res.body
# encoded_params = res_hash["encodedParams"]
encoded_params = "00000000000000000000000001234567890abcdef01234567890abcdef0123450000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000004065336230633434323938666331633134396166626634633839393666623932343237616534316534363439623933346361343935393931623738353262383535"

puts ""
puts "encoded params: " + encoded_params
payload = '0x' + code + encoded_params

puts ""
puts "payload: " + payload

# Payload is the same in Node.js as well as in Ruby

tx = Eth::Tx.new({
	nonce: 1048576,
	data: payload,
	value: 0,
	gas_price: 20697833099,
	gas_limit: 3000000
})

# Sign transaction with private key and get hex
tx.sign keys
raw = tx.hex

puts ""
puts "raw " + raw
```

Which prints raw transaction code:
```
f90d4e831000008504d1afde8b832dc6c08080b90cf830783630363036303430353236303031363030303630303035303535363030303630303436303030363130313030306138313534383136306666303231393136393038333032313739303535353036303430353136313035646233383033383036313035646238333339383130313630343035323830383035313930363032303031393039313930383035313832303139313930363032303031353035303562333336303031363030303631303130303061383135343831373366666666666666666666666666666666666666666666666666666666666666666666666666666666303231393136393038333032313739303535353038313630303236303030363130313030306138313534383137336666666666666666666666666666666666666666666666666666666666666666666666666666666630323139313639303833303231373930353535303830363030333630303035303930383035313930363032303031393038323830353436303031383136303031313631353631303130303032303331363630303239303034393036303030353236303230363030303230393036303166303136303230393030343831303139323832363031663130363130306633353738303531363066663139313638333830303131373835353536313031323435363562383238303031363030313031383535353832313536313031323435373931383230313562383238313131313536313031323335373832353138323630303035303535393136303230303139313930363030313031393036313031303535363562356235303930353036313031346639313930363130313331353635623830383231313135363130313462353736303030383138313530363030303930353535303630303130313631303133313536356235303930353635623530353034323630303536303030353038313930353535303562353035303631303436663830363130313663363030303339363030306633363036303630343035323336313536313030376635373630303033353763303130303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303930303438303633316233303132613331343631303038343537383036333164313433383438313436313031303435373830363333386166336565643134363130313432353738303633353466643464353031343631303138303537383036333633643235366365313436313031613835373830363336356232613836333134363130316432353738303633623830373737656131343631303232643537363130303766353635623631303030323536356233343631303030323537363130303936363030343830353035303631303235353536356236303430353138303830363032303031383238313033383235323833383138313531383135323630323030313931353038303531393036303230303139303830383338333832393036303030363030343630323038343630316630313034363030333032363030663031663135303930353039303831303139303630316631363830313536313030663635373830383230333830353136303031383336303230303336313031303030613033313931363831353236303230303139313530356235303932353035303530363034303531383039313033393066333562333436313030303235373631303131363630303438303530353036313032663635363562363034303531383038323733666666666666666666666666666666666666666666666666666666666666666666666666666666663136383135323630323030313931353035303630343035313830393130333930663335623334363130303032353736313031353436303034383035303530363130333163353635623630343035313830383237336666666666666666666666666666666666666666666666666666666666666666666666666666666631363831353236303230303139313530353036303430353138303931303339306633356233343631303030323537363130313932363030343830353035303631303334323536356236303430353138303832383135323630323030313931353035303630343035313830393130333930663335623334363130303032353736313031626136303034383035303530363130333462353635623630343035313830383231353135383135323630323030313931353035303630343035313830393130333930663335623334363130303032353736313032326236303034383038303335393036303230303139303832303138303335393036303230303139313931393038303830363031663031363032303830393130343032363032303031363034303531393038313031363034303532383039333932393139303831383135323630323030313833383338303832383433373832303139313530353035303530353035303930393039313930353035303631303335653536356230303562333436313030303235373631303233663630303438303530353036313034363635363562363034303531383038323831353236303230303139313530353036303430353138303931303339306633356236303033363030303530383035343630303138313630303131363135363130313030303230333136363030323930303438303630316630313630323038303931303430323630323030313630343035313930383130313630343035323830393239313930383138313532363032303031383238303534363030313831363030313136313536313031303030323033313636303032393030343830313536313032656535373830363031663130363130326333353736313031303038303833353430343032383335323931363032303031393136313032656535363562383230313931393036303030353236303230363030303230393035623831353438313532393036303031303139303630323030313830383331313631303264313537383239303033363031663136383230313931356235303530353035303530383135363562363030313630303039303534393036313031303030613930303437336666666666666666666666666666666666666666666666666666666666666666666666666666666631363831353635623630303236303030393035343930363130313030306139303034373366666666666666666666666666666666666666666666666666666666666666666666666666666666313638313536356236303030363030303530353438313536356236303034363030303930353439303631303130303061393030343630666631363831353635623630303136303030393035343930363130313030306139303034373366666666666666666666666666666666666666666666666666666666666666666666666666666666313637336666666666666666666666666666666666666666666666666666666666666666666666666666666631363333373366666666666666666666666666666666666666666666666666666666666666666666666666666666313631343135313536313033626135373631303030323536356236303031363030343630303036313031303030613831353438313630666630323139313639303833303231373930353535303766323636303935623561663765323332333736306665663135316631643738383936373430636432636331623733613633353766663965346333666461653734303831363034303531383038303630323030313832383130333832353238333831383135313831353236303230303139313530383035313930363032303031393038303833383338323930363030303630303436303230383436303166303130343630303330323630306630316631353039303530393038313031393036303166313638303135363130343535353738303832303338303531363030313833363032303033363130313030306130333139313638313532363032303031393135303562353039323530353035303630343035313830393130333930613135623530353635623630303536303030353035343831353630303030303030303030303030303030303030303030303030313233343536373839306162636465663031323334353637383930616263646566303132333435303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303034303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030343036353333363233303633333433343332333933383636363333313633333133343339363136363632363633343633333833393339333636363632333933323334333233373631363533343331363533343336333433393632333933333334363336313334333933353339333933313632333733383335333236323338333533351ca04baaee3c4b0e6b3bb1ed6cc185a0d76f5cb39c5f1a757c650024e6fa25679b24a07cf4705ee1d424426d1302358fe57e016e90ef63e7fc1f5dd66ec5716ce8417f
```

Node.js code:
```
// Dependencies
var Tx = require('ethereumjs-tx');
var request = require('request');

// Import key object
var privateKey = new Buffer("1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef", 'hex');

// Contract constructor args
var hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855";
var beneficiaryAddress = "0x01234567890abcdef01234567890abcdef012345" // arbitrary address
var params = [beneficiaryAddress, hash]

// ABI + code
var abi = [{"constant":true,"inputs":[],"name":"dataHash","outputs":[{"name":"","type":"string"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"issuer","outputs":[{"name":"","type":"address"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"beneficiary","outputs":[{"name":"","type":"address"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"version","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"revoked","outputs":[{"name":"","type":"bool"}],"payable":false,"type":"function"},{"constant":false,"inputs":[{"name":"_reason","type":"string"}],"name":"revoke","outputs":[],"payable":false,"type":"function"},{"constant":true,"inputs":[],"name":"timestamp","outputs":[{"name":"","type":"uint256"}],"payable":false,"type":"function"},{"inputs":[{"name":"_beneficiary","type":"address"},{"name":"_dataHash","type":"string"}],"type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"name":"reason","type":"string"}],"name":"CertificateRevoked","type":"event"}]
var code = "606060405260016000600050556000600460006101000a81548160ff021916908302179055506040516105db3803806105db833981016040528080519060200190919080518201919060200150505b33600160006101000a81548173ffffffffffffffffffffffffffffffffffffffff0219169083021790555081600260006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908302179055508060036000509080519060200190828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106100f357805160ff1916838001178555610124565b82800160010185558215610124579182015b82811115610123578251826000505591602001919060010190610105565b5b50905061014f9190610131565b8082111561014b5760008181506000905550600101610131565b5090565b5050426005600050819055505b505061046f8061016c6000396000f36060604052361561007f576000357c0100000000000000000000000000000000000000000000000000000000900480631b3012a3146100845780631d1438481461010457806338af3eed1461014257806354fd4d501461018057806363d256ce146101a857806365b2a863146101d2578063b80777ea1461022d5761007f565b610002565b34610002576100966004805050610255565b60405180806020018281038252838181518152602001915080519060200190808383829060006004602084601f0104600302600f01f150905090810190601f1680156100f65780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b346100025761011660048050506102f6565b604051808273ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b3461000257610154600480505061031c565b604051808273ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34610002576101926004805050610342565b6040518082815260200191505060405180910390f35b34610002576101ba600480505061034b565b60405180821515815260200191505060405180910390f35b346100025761022b6004808035906020019082018035906020019191908080601f01602080910402602001604051908101604052809392919081815260200183838082843782019150505050505090909190505061035e565b005b346100025761023f6004805050610466565b6040518082815260200191505060405180910390f35b60036000508054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156102ee5780601f106102c3576101008083540402835291602001916102ee565b820191906000526020600020905b8154815290600101906020018083116102d157829003601f168201915b505050505081565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b600260009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b60006000505481565b600460009054906101000a900460ff1681565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff161415156103ba57610002565b6001600460006101000a81548160ff021916908302179055507f266095b5af7e2323760fef151f1d78896740cd2cc1b73a6357ff9e4c3fdae7408160405180806020018281038252838181518152602001915080519060200190808383829060006004602084601f0104600302600f01f150905090810190601f1680156104555780820380516001836020036101000a031916815260200191505b509250505060405180910390a15b50565b6005600050548156"

// var body = { abi: abi, params: params };
// request({ url: 'http://127.0.0.1:5000/api/solidity/encodeConstructorParams', method: 'POST', json: body }, function (error, response, body) {
//     if (!error && response.statusCode == 200) {
//     console.error("Request error:", body);
//     }

//     var encodedParams = body.encodedParams;

var encodedParams = "00000000000000000000000001234567890abcdef01234567890abcdef0123450000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000004065336230633434323938666331633134396166626634633839393666623932343237616534316534363439623933346361343935393931623738353262383535";

console.log();
console.log("encoded params: ", encodedParams);

var payload = '0x' + code + encodedParams;

console.log();
console.log("payload: ", payload);


// Payload is the same in Node.js as well as in Ruby

var transaction = new Tx({
    nonce: '0x100000', // 1048576
    data: payload, 
    value: '0x00', // 0
    gasPrice: '0x4D1AFDE8B', // 20697833099
    gasLimit: '0x2DC6C0' // 3000000
});
transaction.sign(privateKey);
var rawTransaction = transaction.serialize().toString('hex');

console.log();
console.log("raw:", rawTransaction);
// });
```

Which prints raw transation hex of 
```
f906d1831000008504d1afde8b832dc6c08080b9067b606060405260016000600050556000600460006101000a81548160ff021916908302179055506040516105db3803806105db833981016040528080519060200190919080518201919060200150505b33600160006101000a81548173ffffffffffffffffffffffffffffffffffffffff0219169083021790555081600260006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908302179055508060036000509080519060200190828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106100f357805160ff1916838001178555610124565b82800160010185558215610124579182015b82811115610123578251826000505591602001919060010190610105565b5b50905061014f9190610131565b8082111561014b5760008181506000905550600101610131565b5090565b5050426005600050819055505b505061046f8061016c6000396000f36060604052361561007f576000357c0100000000000000000000000000000000000000000000000000000000900480631b3012a3146100845780631d1438481461010457806338af3eed1461014257806354fd4d501461018057806363d256ce146101a857806365b2a863146101d2578063b80777ea1461022d5761007f565b610002565b34610002576100966004805050610255565b60405180806020018281038252838181518152602001915080519060200190808383829060006004602084601f0104600302600f01f150905090810190601f1680156100f65780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b346100025761011660048050506102f6565b604051808273ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b3461000257610154600480505061031c565b604051808273ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34610002576101926004805050610342565b6040518082815260200191505060405180910390f35b34610002576101ba600480505061034b565b60405180821515815260200191505060405180910390f35b346100025761022b6004808035906020019082018035906020019191908080601f01602080910402602001604051908101604052809392919081815260200183838082843782019150505050505090909190505061035e565b005b346100025761023f6004805050610466565b6040518082815260200191505060405180910390f35b60036000508054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156102ee5780601f106102c3576101008083540402835291602001916102ee565b820191906000526020600020905b8154815290600101906020018083116102d157829003601f168201915b505050505081565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b600260009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b60006000505481565b600460009054906101000a900460ff1681565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff161415156103ba57610002565b6001600460006101000a81548160ff021916908302179055507f266095b5af7e2323760fef151f1d78896740cd2cc1b73a6357ff9e4c3fdae7408160405180806020018281038252838181518152602001915080519060200190808383829060006004602084601f0104600302600f01f150905090810190601f1680156104555780820380516001836020036101000a031916815260200191505b509250505060405180910390a15b50565b600560005054815600000000000000000000000001234567890abcdef01234567890abcdef01234500000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000040653362306334343239386663316331343961666266346338393936666239323432376165343165343634396239333463613439353939316237383532623835351ba09301c0eedba45b9121f478123ae847334f132ec2df31735a0a83f239193c2a54a0740dc69c155af1cc6db66b52d225546a0e6b116f1beda36db8fc77608c96d869
```

The both print the same ```payload```:
```
0x606060405260016000600050556000600460006101000a81548160ff021916908302179055506040516105db3803806105db833981016040528080519060200190919080518201919060200150505b33600160006101000a81548173ffffffffffffffffffffffffffffffffffffffff0219169083021790555081600260006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908302179055508060036000509080519060200190828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106100f357805160ff1916838001178555610124565b82800160010185558215610124579182015b82811115610123578251826000505591602001919060010190610105565b5b50905061014f9190610131565b8082111561014b5760008181506000905550600101610131565b5090565b5050426005600050819055505b505061046f8061016c6000396000f36060604052361561007f576000357c0100000000000000000000000000000000000000000000000000000000900480631b3012a3146100845780631d1438481461010457806338af3eed1461014257806354fd4d501461018057806363d256ce146101a857806365b2a863146101d2578063b80777ea1461022d5761007f565b610002565b34610002576100966004805050610255565b60405180806020018281038252838181518152602001915080519060200190808383829060006004602084601f0104600302600f01f150905090810190601f1680156100f65780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b346100025761011660048050506102f6565b604051808273ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b3461000257610154600480505061031c565b604051808273ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b34610002576101926004805050610342565b6040518082815260200191505060405180910390f35b34610002576101ba600480505061034b565b60405180821515815260200191505060405180910390f35b346100025761022b6004808035906020019082018035906020019191908080601f01602080910402602001604051908101604052809392919081815260200183838082843782019150505050505090909190505061035e565b005b346100025761023f6004805050610466565b6040518082815260200191505060405180910390f35b60036000508054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156102ee5780601f106102c3576101008083540402835291602001916102ee565b820191906000526020600020905b8154815290600101906020018083116102d157829003601f168201915b505050505081565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b600260009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b60006000505481565b600460009054906101000a900460ff1681565b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff161415156103ba57610002565b6001600460006101000a81548160ff021916908302179055507f266095b5af7e2323760fef151f1d78896740cd2cc1b73a6357ff9e4c3fdae7408160405180806020018281038252838181518152602001915080519060200190808383829060006004602084601f0104600302600f01f150905090810190601f1680156104555780820380516001836020036101000a031916815260200191505b509250505060405180910390a15b50565b600560005054815600000000000000000000000001234567890abcdef01234567890abcdef0123450000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000004065336230633434323938666331633134396166626634633839393666623932343237616534316534363439623933346361343935393931623738353262383535
```

**Comment by se3000** [comment] 2016-12-12 05:13
It looks like you need to convert the data to binary instead of just passing in a hex string. Sorry for the confusion, the readme example didn't convert it to binary either. I'll fix that immediately.

I'll make this more flexible, but until that fix gets out you can get this working by explicitly converting the `data` value from hex to binary:
```
{ nonce: '0x100016',
  data: Eth::Utils.hex_to_bin(hex_data),
  value: '0x00',
  gasPrice: '0x4d1afde8b',
  gasLimit: '0x2DC6C0' 
}
```

**Comment by se3000** [comment] 2017-01-29 19:35
Ok, released a new version of the gem that accepts hex as data. By default it accepts hex, but if you'd prefer not to change your code, then you can set the configuration back to the original behavior with:
```ruby
Eth.configure do |config|
  config.tx_data_hex = false
end
```

In addition to the `#data` method, which changes based on configuration, there is `#data_hex` and `#data_bin`, whose return values will not change.

Closing this issue, feel free to reopen if you continue to experience issues.

**Closed by se3000** 2017-01-29 19:35 UTC
