### ISSUE TITLE
Unsafe loading of Libcrypto preventing Rails console+server development

### ISSUE THREAD

**Issue by PositiveControl** [se3000/ruby-eth#67] opened 2021-11-28 22:10 UTC
```
% rails s
WARNING: /Users/pc/.rvm/rubies/ruby-3.0.0/bin/ruby is loading libcrypto in an unsafe way
zsh: abort      rails s
```

Apparently MacOS (or the M1 specifically), Rails or even Ruby doesn't like the way `libcrypto` is loaded and prevents consoles or servers from starting when the gem is included.

```
% rails -v
Rails 6.1.4.1
% ruby -v
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin21]

# eth version
eth (0.4.16)
```

I've tested this assumption by bundling without `eth` and do not encounter the `libcrypto` errors.

Cheers.

**Comment by q9f** [comment] 2021-11-29 09:03
Thanks for reporting. I'll probably have a fix by end of week.

The `eth` gem is fixed in #66 but `libcrypto` specifically fails on the `money-tree` dependency, see https://github.com/GemHQ/money-tree/pull/43 

Closing as duplicate of #47 which tracks all ssl/crypto issues on macos.

**Closed as completed by q9f** 2021-11-29 09:03 UTC
